server:
  host: localhost
  port: 18081

spring:
  profiles:
    default: dev
  application:
    name: user-server

# jwt
jwt:
  secret:
    key: 09f001b9896c05dc6d2c353da804aa7e5d14622943889409dce157a8793af945067b8f07570c97529e1bed70ee339398c3fb576ba4547e2162ab9ea9aa365483

eureka:
  client:
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true        # Eureka 서버로부터 서비스 조회
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /user-server/swagger-ui
  api-docs:
    path: /user-server/v3/api-docs