spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${server.host}:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  host: localhost